YEP - Updated Badwords and Links
NotEnoughUpdates/bush-bot pull request #23
Opened 2021-09-09 00:21 UTC by jani270

Hi, in this change ill add 2 Scamlinks (normal) and these 2 other words. I think adding them and enforcing our NSFW Rule would make Moulberry Bush and the general chat there are better place. In the last few weeks the chat there is most of the time very unreadable and contains just the words "sex", "horny", "fuck me" or smth else. 

If you dont want these changes just remove them, but please iron think about them.

2021-09-09 00:23 UTC, IRONM00N commented
ill have to refactor this but I need to think about it

2021-09-09 00:25 UTC, jani270 commented
> ill have to refactor this but I need to think about it

Oky maybe a discussion in staff chat would be also good idk how other staffs see that

2021-09-09 20:01 UTC, IRONM00N commented
I'm not sure automod is the best way to address this, it has no awareness to context

2021-09-11 14:17 UTC, IRONM00N commented on lib/badwords.json5
> +	'sex': 0,
```suggestion

```

2021-09-11 14:17 UTC, IRONM00N commented on lib/badwords.json5
> +	'cum': 0,
```suggestion
```

2021-09-11 14:18 UTC, IRONM00N commented on lib/badwords.json5
> +	'seggs': 0,
```suggestion
```

2021-09-11 14:18 UTC, IRONM00N commented on lib/badwords.json5
> +	'cock': 0,
```suggestion
```

2021-09-11 14:18 UTC, IRONM00N requested changes
I am going to be implementing these a different way

2021-09-17 21:11 UTC, IRONM00N approved these changes

2021-09-17 21:11 UTC, merged