Appeal listener
NotEnoughUpdates/bush-bot pull request #57
Opened 2022-03-03 15:29 UTC by TymanWasTaken

Automattically fetches user and modlogs for submitted appeals and creates a thread with it

2022-03-04 13:08 UTC, IRONM00N requested changes

2022-03-04 13:08 UTC, IRONM00N commented on src/listeners/bush/appealListener.ts
> +						.addField({
```suggestion
						.addFields({
```
discord.js removed addField

2022-03-04 13:08 UTC, IRONM00N commented on src/listeners/bush/appealListener.ts
> +						.embed()
no gross

2022-03-05 20:59 UTC, TymanWasTaken commented on src/listeners/bush/appealListener.ts
> +						.embed()
??????

2022-03-05 21:08 UTC, IRONM00N commented on src/listeners/bush/appealListener.ts
> +						.embed()
just import Embed

2022-03-08 03:44 UTC, IRONM00N approved these changes

2022-03-08 03:44 UTC, merged